# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# set working directory
WORKDIR /app

# copy package and tsconfig
COPY package.json package-lock.json tsconfig.json ./

# copy source
COPY src ./src

# install dependencies and build
RUN npm install && npm run build && npm prune --production

# default command to start MCP server
CMD ["node", "dist/index.js"]
